image: continuumio/miniconda3:latest

# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- security
- designchecks
sast:
  stage: security
include:
- template: Security/SAST.gitlab-ci.yml
design:
  stage: designchecks
  script:
    - apt-get update -q -y
    - apt-get install -y build-essential
    - conda create -n cadquery
    - source activate cadquery
    - conda install -c conda-forge -c cadquery cadquery=master
    - python -c "from .checks.manufacturability import run_checks;run_checks()"
